apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: carmicroservice
  name: carmicroservice
spec:
  ports:
    - name: "5052"
      port: 5052
      targetPort: 80
  selector:
    io.kompose.service: carmicroservice
status:
  loadBalancer: {}
