apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: carmicroservice
  name: carmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: carmicroservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: carmicroservice
    spec:
      containers:
        - image: carmicroservice
          name: carmicroservice
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
