auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: admin
  managementUser: manager
  managementPassword: manager
proxyAddressForwarding: true
ingress:
  enabled: true
  hostname: keycloak.kind.cluster
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  tls: true
  ingressClassName: nginx
postgresql:
  enabled: true
  auth:
    postgresPassword: password
    password: password